# Configure this Discovery Server
eureka:
  instance:
    hostname: ${ORA_APP_NAME}
  client:  # Not a client, don't register with yourself
    registerWithEureka: false
    fetchRegistry: false
     
server:
  port: ${PORT}   # HTTP (Tomcat) port

# Discovery Server Dashboard uses FreeMarker.  Don't want Thymeleaf templates
spring:
  thymeleaf:
    enabled: false     # Disable Thymeleaf 